sudo: false
language: cpp
compiler:
 - gcc
 - clang
cache:
  directories:
    - $HOME/.ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
install:
 - ./scripts/install-breakpad.sh
script:
 - export PKG_CONFIG_PATH=/tmp/usr/lib/pkgconfig:${PKG_CONFIG_PATH}
 - ./autogen.sh
 - ./configure
 - make check -j4