sudo: false
language: cpp
compiler:
 - gcc
 - clang
# addons:
#   apt:
#     packages:
#       - net-tools
cache:
  directories:
    - $HOME/.ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
install:
 - ./scripts/install-breakpad
script:
 - ./autogen.sh && 